include: package:flutter_lints/flutter.yaml

linter:
  rules:
    sized_box_for_whitespace: true
    sized_box_shrink_expand: true
    require_trailing_commas: true
    curly_braces_in_flow_control_structures: true
    always_declare_return_types: true
    avoid_function_literals_in_foreach_calls: true
    prefer_is_empty: true
    eol_at_end_of_file: true
    prefer_interpolation_to_compose_strings: true
    unnecessary_lambdas: true
    prefer_void_to_null: true
    unrelated_type_equality_checks: true
    unnecessary_statements: true
    cancel_subscriptions: true
    avoid_print: false
