name: Android APK Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Android build
        uses: ./.github/actions/android-build-prepare
        with:
          app-dir: open_wearable
          analyze: "true"

      - working-directory: open_wearable
        run: flutter build apk --release
      - uses: actions/upload-artifact@v6
        with:
          name: main-release-apk-${{ github.sha }}
          path: open_wearable/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
